### ISSUE TITLE
Universal

### ISSUE THREAD

**Issue by GVeidenberg** [centralnic-reseller/whmcs-domainimporter#7]
Hello

Can this be made as a universal importer? Currently, your module only allows importing RRPROXY and Hexonet registrar domains. 

But can this restriction be moved? To allow domain import

Thanks

**Comment by KaiSchwarz-cnic** [comment]
Hi @GVeidenberg,

basically, we are open to extend this on demand, but still aligned to our priorities. We offer this only to CentralNic related Registrar Brands (HEXONET, RRPproxy which will be renamed to CentralNic Reseller soon, internet.bs and TPP Wholesale). I noticed that you've opened an issue with internet.bs as well - is this feature request about supporting internet.bs?
It is also a question for us having access to the source code of the underlying registrar module as we have to apply some additional code to it.

That said: if your request is about getting internet.bs supported, we can have an eye on it. But it probably takes weeks to finish this.

There's another built-in possibility of WHMCS that you can use to import single (non-premium!) domain names.
Read here: https://docs.whmcs.com/Migration_Guide#Adding_Domains

HTH
Kai

**Comment by GVeidenberg** [comment]
Hi. I would love you to remove the registrar's choice of only 2 registrars. So I can choose all registrars. 

As far as I understand I do not need the fancy part where the script creates a new account etc.

I need just that script add-s domains I input to the account I choose.

**Comment by KaiSchwarz-cnic** [comment]
Again, we do not support other registrar brands (our competitors) with our features. We can extend this in direction of Registrar Brands of the CentralNic Group where we have access to the registrar module's source code as well.

**Comment by GVeidenberg** [comment]
Again, I am not asking for your support. 
I am asking if you can remove the limit for me. One version without your limit as which registrar I can choose.

Thank You

**Comment by KaiSchwarz-cnic** [comment]
Not sure why you're following up. I explained why we do not plan to do that in general.
